services:
  server:
    image: ghcr.io/yelosheng/clipboard-push-server:latest
    ports:
      - "5055:5055"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
